import * as core from "@actions/core";
import * as github from "@actions/github";
import type { RadarConfig } from "../config";
import type { ClassifiedCandidate } from "../sources/types";
import { withRetry } from "../utils/retry";
import { normalizeUrl } from "../filter/dedup";

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function buildIssueTitle(candidate: ClassifiedCandidate, config: RadarConfig): string {
  const prefix = config.issue_template.title_prefix;
  return `${prefix} ${escapeTableCell(candidate.title).slice(0, 200)}`;
}

function renderTemplate(template: string, candidate: ClassifiedCandidate): string {
  return template
    .replace(/\{\{name\}\}/g, candidate.title)
    .replace(/\{\{url\}\}/g, candidate.url)
    .replace(/\{\{description\}\}/g, candidate.description.slice(0, 100))
    .replace(/\{\{language\}\}/g, candidate.metadata.language ?? "")
    .replace(/\{\{stars\}\}/g, String(candidate.metadata.stars ?? ""))
    .replace(/\{\{license\}\}/g, String((candidate.metadata as Record<string, unknown>).license ?? ""))
    .replace(/\{\{source\}\}/g, candidate.source)
    .replace(/\{\{category\}\}/g, candidate.suggestedCategory);
}

function buildIssueBody(candidate: ClassifiedCandidate, config: RadarConfig): string {
  const lines = [
    `## Candidate Resource`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
  ];

  const allFields: Record<string, () => string | null> = {
    url: () => `| **URL** | ${escapeTableCell(candidate.url)} |`,
    source: () => `| **Source** | ${escapeTableCell(candidate.source)} |`,
    relevanceScore: () => `| **Relevance Score** | ${candidate.relevanceScore}/100 |`,
    suggestedCategory: () => `| **Suggested Category** | ${escapeTableCell(candidate.suggestedCategory)} |`,
    tags: () => candidate.suggestedTags.length > 0 ? `| **Tags** | ${candidate.suggestedTags.map((t) => `\`${escapeTableCell(t)}\``).join(", ")} |` : null,
    stars: () => candidate.metadata.stars !== undefined ? `| **Stars** | ${candidate.metadata.stars} |` : null,
    language: () => candidate.metadata.language ? `| **Language** | ${escapeTableCell(candidate.metadata.language)} |` : null,
    authors: () => candidate.metadata.authors?.length ? `| **Authors** | ${escapeTableCell(candidate.metadata.authors.join(", "))} |` : null,
  };

  const fieldsToShow = config.issue_template.include_fields ?? Object.keys(allFields);
  for (const field of fieldsToShow) {
    if (allFields[field]) {
      const row = allFields[field]();
      if (row) lines.push(row);
    }
  }

  const suggestedEntry = config.issue_template.suggested_entry_format
    ? renderTemplate(config.issue_template.suggested_entry_format, candidate)
    : `- [${candidate.title}](${candidate.url}) - ${candidate.description.slice(0, 100)}`;

  if (candidate.metadata.license) {
    lines.push(
      `| **License** | ${escapeTableCell(candidate.metadata.license)} |`
    );
  }

  if (candidate.metadata.archived !== undefined) {
    lines.push(
      `| **Archived** | ${candidate.metadata.archived ? "Yes" : "No"} |`
    );
  }

  if (candidate.metadata.fork !== undefined) {
    lines.push(
      `| **Fork** | ${candidate.metadata.fork ? "Yes" : "No"} |`
    );
  }

  if (candidate.metadata.owner) {
    lines.push(
      `| **Owner** | ${escapeTableCell(candidate.metadata.owner)} |`
    );
  }

  if (candidate.metadata.homepage) {
    lines.push(
      `| **Homepage** | ${escapeTableCell(candidate.metadata.homepage)} |`
    );
  }

  if (candidate.metadata.lastPushedAt) {
    lines.push(
      `| **Last Pushed** | ${escapeTableCell(candidate.metadata.lastPushedAt)} |`
    );
  }

  lines.push(
    ``,
    `## Description`,
    ``,
    "```",
    (candidate.description || "No description available").slice(0, 1000),
    "```",
    ``,
    `## LLM Reasoning`,
    ``,
    "```",
    (candidate.reasoning || "No reasoning provided").slice(0, 500),
    "```",
    ``,
    `## Suggested Entry`,
    ``,
    `\`\`\`markdown`,
    suggestedEntry,
    `\`\`\``,
    ``,
    `---`,
    `*Generated by [awesome-list-radar](https://github.com/moven0831/awesome-list-radar)*`
  );

  return lines.join("\n");
}

export interface IssueClient {
  listIssues(labels: string[]): Promise<{ title: string; body?: string }[]>;
  createIssue(
    title: string,
    body: string,
    labels: string[]
  ): Promise<{ number: number; html_url: string }>;
}

function makeGitHubClient(token: string): IssueClient {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  return {
    async listIssues(labels: string[]) {
      const allIssues: { title: string; body?: string }[] = [];
      let page = 1;
      const perPage = 100;

      // eslint-disable-next-line no-constant-condition
      while (true) {
        const { data } = await octokit.rest.issues.listForRepo({
          owner,
          repo,
          state: "all",
          labels: labels.join(","),
          per_page: perPage,
          page,
        });

        for (const i of data) {
          allIssues.push({ title: i.title, body: i.body ?? undefined });
        }

        if (data.length < perPage) break;
        page++;
      }

      core.info(
        `Fetched ${allIssues.length} existing issues (open+closed) for dedup`
      );
      return allIssues;
    },

    async createIssue(title: string, body: string, labels: string[]) {
      const { data } = await octokit.rest.issues.create({
        owner,
        repo,
        title,
        body,
        labels,
      });
      return { number: data.number, html_url: data.html_url };
    },
  };
}

export async function createIssues(
  candidates: ClassifiedCandidate[],
  config: RadarConfig,
  dryRun: boolean,
  client?: IssueClient
): Promise<number> {
  if (candidates.length === 0) return 0;

  const labels = config.issue_template.labels;
  const issueClient =
    client ?? makeGitHubClient(core.getInput("github_token"));

  // Fetch existing issues for idempotency check
  let existingIssues: { title: string; body?: string }[] = [];
  try {
    existingIssues = await withRetry(() => issueClient.listIssues(labels));
  } catch (error) {
    core.warning(
      `Could not fetch existing issues: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  const existingUrls = new Set(
    existingIssues
      .map((issue) => {
        const match = issue.body?.match(
          /\| \*\*URL\*\* \| (https?:\/\/[^\s|]+)/
        );
        return match?.[1] ? normalizeUrl(match[1]) : undefined;
      })
      .filter((url): url is string => url !== undefined)
  );

  let created = 0;

  for (const candidate of candidates) {
    if (existingUrls.has(normalizeUrl(candidate.url))) {
      core.info(
        `Skipping "${candidate.title}" — issue already exists for ${candidate.url}`
      );
      continue;
    }

    const title = buildIssueTitle(candidate, config);
    const body = buildIssueBody(candidate, config);

    if (dryRun) {
      core.info(`[DRY RUN] Would create issue: ${title}`);
      core.info(`  URL: ${candidate.url}`);
      core.info(`  Score: ${candidate.relevanceScore}`);
      created++;
      continue;
    }

    try {
      const issue = await withRetry(() =>
        issueClient.createIssue(title, body, labels)
      );
      core.info(`Created issue #${issue.number}: ${issue.html_url}`);
      created++;
    } catch (error) {
      core.warning(
        `Failed to create issue for "${candidate.title}": ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }

  return created;
}

export { buildIssueTitle, buildIssueBody, escapeTableCell, renderTemplate };
